// Mocks generated by Mockito 5.4.4 from annotations
// in lms_quotes_app/test/quotes_controller_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:lms_quotes_app/repository/quotes_repository.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [QuotesRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockQuotesRepository extends _i1.Mock implements _i2.QuotesRepository {
  @override
  String get dummyJson => (super.noSuchMethod(
        Invocation.getter(#dummyJson),
        returnValue: _i3.dummyValue<String>(
          this,
          Invocation.getter(#dummyJson),
        ),
        returnValueForMissingStub: _i3.dummyValue<String>(
          this,
          Invocation.getter(#dummyJson),
        ),
      ) as String);

  @override
  _i4.Future<List<_i2.Quote>> fetchQuotes() => (super.noSuchMethod(
        Invocation.method(
          #fetchQuotes,
          [],
        ),
        returnValue: _i4.Future<List<_i2.Quote>>.value(<_i2.Quote>[]),
        returnValueForMissingStub:
            _i4.Future<List<_i2.Quote>>.value(<_i2.Quote>[]),
      ) as _i4.Future<List<_i2.Quote>>);
}
